sudo: required
services:
    - docker
before_install:
    - docker build -t abhishekjha26/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true abhishekjha26/react-test npm test

after_success:
    - docker build -t abhishekjha26/multi-client ./client
    - docker build -t abhishekjha26/multi-nginx ./nginx
    - docker build -t abhishekjha26/multi-server ./server
    - docker build -t abhishekjha26/multi-worker ./worker
# log into the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push to docker hub
    - docker push abhishekjha26/multi-client
    - docker push abhishekjha26/multi-nginx
    - docker push abhishekjha26/multi-server
    - docker push abhishekjha26/multi-worker
deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: Docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-139522873616
    bucket_path: docker-multi
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY